### ISSUE TITLE
Trailing comma in FSharp.Javascript.js, line 1825

### ISSUE THREAD

**Issue by wmeyer** [jgreene/FSharp.Javascript#1]
There is a trailing comma after "Zip3: Microsoft.FSharp.Collections.SeqModule.Zip3". 

Some browsers do not like such commas which I noticed when I did some testing with Windows.Forms.WebBrowser (so Internet Explorer will probably have a problem with trailing commas, too).

Otherwise the library seems to work great so far. Pretty cool to write your Javascript in F#!

**Comment by jgreene** [comment]
Thanks for the heads up, this should be fixed now.
